version: "3.9"

services:

  db:
    image: postgres
    container_name: bot_lsgu_db
    volumes:
      - ./db_data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - '5432:5432'
    restart: always

  bot_lsgu:
    command: python run_bot.py
    # instead of 'build'
    # image: 'репозиторий'
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    container_name: bot_lsgu
    volumes:
      - ./src:/app
    depends_on:
      - db
